### ISSUE TITLE
Wifi C2Plugin

### ISSUE THREAD

**Issue by AElkenawy** [rexrainbow/C2_plugins#1]
Hello 
can i find a Wifi plugin which measure signal strength ??
 if i can't , can i convert a phonegap files (www , src .... etc) files to a C2 plugin and how ?? 

Thanks in advance

**Comment by rexrainbow** [comment]
I did not make phonegap, please send message to [cranberrygame](https://www.scirra.com/forum/construct2-cordova-plugins-plugins_t164385)

**Comment by AElkenawy** [comment]
i think that cranberrygame services aren't for free :D

**Comment by rexrainbow** [comment]
It should not be free. Testing on mobile devices are not free.
