### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by blurymind** [rexrainbow/C2_plugins#4]
Hi @rexrainbow , I am a big fan of your work and have been folowing it for years.
I was wondering if its ok to use some of the code outside of construct.

Does the license prohibit their use outside of construct2 engine and are you personaly ok with that?

Would you be glad if some of them get ported to other game engines?
We have been working on implementing a js extension framework in another game engine that can really do with some new extensions to stress test it. I don't know if you'd be interested in getting involved or giving us some feedback :)

**Comment by rexrainbow** [comment]
@blurymind 

Sorry I don't have time to port my plugins to other game engine recently, I am focusing on [phaser3](https://github.com/photonstorm/phaser) now. 
I am interesting in building an isolated library to help you porting (i.e. pure logic, you still need to add some code to connect the target engine), and it also could be reused in my phaser3 plugins. 
Which plugins will you port?

**Comment by blurymind** [comment]
@rexrainbow It will really help if you make them as isolated libraries and it will be a good way to give them a new life with open source game engines. 
Btw I love phaser3 too :) Awesome choice!

On the engine side, @4ian is currently in the process of implementing a js addon system in gdevelop 5. 

https://github.com/4ian/GD/blob/373c55ddc54349130b86d2b718fdd886079a8744/newIDE/README-extensions.md
You have a lot of exerience with js extensions, so I was wondering if we can get some of your feedback on it - when the system becomes more feature complete and you have some time of course. 

I wonder how feasible would it be to take the abstract functionality and expose it to gdevelop's  IDE. I can try to port some of them to the gdevelop5's new extension framework :) If you offer to help me in the process, then if I get stuck at some stage - would you be ok with helping me figure it out? Or maybe if you have some advice on how to go about this?

I still haven't completely decided on which ones to port yet, but for now I must start with simpler ones - while the js extension framework is not complete yet. Can you recomend ones that you think would be a nice and easy start?

Btw thank you for making all of these wonderful extensions. Your work is a great inspiration to me 👍

**Comment by rexrainbow** [comment]
@blurymind 

It seems that there are so many 3rd-party plugins could be added into gdevelop, for example a bbcode text object plugin.
And yes, I agree that it is not easy to create an isolated logic library. I had used some helper of phaser3 in my plugins already. It will be a lot of coping job if I try to isolate my plugins.
Anyway, you could reference my c2 plugins, grab code from them, port to your gdevelop plugins.

**Comment by blurymind** [comment]
@rexrainbow I was actually thinking of making a bbcode plugin , but that will happen when the extension system gets support for game objects :) 

Thank you for approving any code borrowing. If I end up using it, I will include your name in the plugin's description. Credit goes where its due :) 
My hope is that one day gdevelop will have a rich library of js plugins in a repository like this one- and even better- with the best ones included with the engine.

I had a look at your phaser work- you have made some very cool extensions for it already

**Comment by rexrainbow** [comment]
@blurymind 

I feel that you will pay lots of effort for integrating, thus it might be not necessary to put my name in your plugin description, imo.

**Comment by blurymind** [comment]
@rexrainbow it will be an interesting experiment for me :) 
I am really excited about the new extension framework in gdevelop!
