### ISSUE TITLE
Upload Plugins Request?

### ISSUE THREAD

**Issue by invaderxyz** [rexrainbow/C2_plugins#5]
Hi, I have an old C2 project I've been needing to open, and unfortunately it requires a couple of old/defunct plugins that I used to use for Multiplayer, before Multiplayer became a standard plugin in C2.

- Bottleneck
- Function
- Lobby
- Chat
- Sync-Function

If you can, do you think you could upload these plugins temporarily so that I may download them and open up my old project? It would be amazing if you could, thanks!

**Comment by rexrainbow** [comment]
@invaderxyz 

Sorry I had left scirra in early of this year, no supporting now.
